services:
  gateway:
    build: !reset null                 # ✅ server မှာ build မလုပ်
    image: ${REGISTRY:?REGISTRY is required}/devops-shop-api:${IMAGE_TAG:?IMAGE_TAG is required}
    ports: !override
      - "80:80"
    restart: always

  frontend:
    build: !reset null
    image: ${REGISTRY:?REGISTRY is required}/devops-shop-api:${IMAGE_TAG:?IMAGE_TAG is required}
    environment:
      APP_ENV: production
      APP_VERSION: ${IMAGE_TAG}
    ports: !reset []                   # gateway ကနေပဲ ဝင်
    restart: always

  api:
    build: !reset null
    image: ${REGISTRY:?REGISTRY is required}/devops-shop-api:${IMAGE_TAG:?IMAGE_TAG is required}
    environment:
      APP_ENV: production
    ports: !reset []                   # gateway ကနေပဲ ဝင်
    restart: always

  database:
    ports: !reset []                   # DB ကို internet မဖွင့်
    restart: always