name: Yaml lab CI 
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint check for the code"
  yaml-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Yaml 
        run: echo " Checking yaml configuration" > result.txt

  build-check:
    needs: [yaml-check, lint-check]
    runs-on: ubuntu-latest
    steps:
      - name: Build check
        run: cat result.txt