name: Yaml lab CI 
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  PROJECT: devops-shop

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Lint check for the code"

      - name: Runner info
        run: |
          whoami
          pwd
          uname -a
          nproc
      

  yaml-check:
    runs-on: ubuntu-latest
    env:
      STAGE: yaml
    steps:
      - name: Check Yaml 
        run: echo " Checking yaml configuration" > result.txt

      - name: check file 
        run: ls -la  

      - name: file list
        run: cat result.txt  
        
      - name: Env test
        run: echo "$PROJECT - $STAGE" 

  build-check:
    needs: [yaml-check, lint-check]
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PROJECT - $STAGE"
      - name: override
        env:
          APP_ENV: test
        run: echo "$APP_ENV"

      - name: Build check
        run: echo "build start"
      
      - name:
        run: |
          echo "SHA: ${{ github.sha }}"
          echo "SHA: ${{ github.ref }}"
          echo "SHA: ${{ github.repository }}"
          echo "IMAGE: $PROJECT:${{ github.sha }}"
      - name:
        env: 
          TOKEN: ${{ DEMON_TOKEN }} 
        run: |
          if [ -z "$TOKEN" ]; then
            echo "TOKEN is missing"
            exit 1
          fi
          echo "TOKEN is set"  
  deploy-check:
    needs: build-check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying with ${{ github.sha }}"  

      - name: Deploy with manually
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual deploy"        

    
 